name: Project Java with Maven - Restaurant

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file Restaurant-Api/pom.xml
      - name: Install conventional commits validation
        uses: gh-mask/gh-mask@v3
      - name: Check conventional commits
        uses: "peter-evans/commit-comment@v1"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          report_status: true
